float64[] initial_configuration
geometry_msgs/Pose goal_pose
geometry_msgs/Pose ifco_pose
BoundingBoxWithPose[] bounding_boxes_with_poses
float64[3] position_deltas
# euler XYZ
float64[3] orientation_deltas
AllowedCollision[] allowed_collisions
---
bool success
float64[] final_configuration
