string problemID
float64[] joints
geometry_msgs/Pose goalFrame
float64[3] boxSize
geometry_msgs/Quaternion boxOrientation
uint32 sampleAttempts
string collObject
---
bool success
float64[] finalJoints
