# Random seed, used for sampling functions. If 0, unix time will be used.
uint32 seed

# The initial joint configuration of the robot.
float64[] initial_configuration

# The goal pose of the pregrasp phase.
geometry_msgs/Pose pregrasp_goal_pose

# The goal pose of the go down phase.
geometry_msgs/Pose go_down_goal_pose

# The goal pose of the slide phase.
geometry_msgs/Pose slide_goal_pose

# The pose of the IFCO container in the robot base frame.
geometry_msgs/Pose ifco_pose

# An array of bounding boxes with poses. Check BoundingBoxWithPose.msg
# for more details. The box_id in allowed_collisions is the same as position
# in this array.
BoundingBoxWithPose[] bounding_boxes_with_poses

# The definition of the pregrasp manifold.
WallGraspPregraspManifold pregrasp_manifold

# An array of allowed collisions in the go down phase. Check AllowedCollision.msg for more details.
# A collision that is not listed here will trigger a failure.
# Every collision in pregrasp phase is a failure.
AllowedCollision[] go_down_allowed_collisions

# An array of allowed collisions in the slide phase.
AllowedCollision[] slide_allowed_collisions
---
# No feasible trajectories were found.
uint8 FAILED=0
# Pregrasp to pregrasp_goal_pose and consequent go down to go_down_goal_pose is feasible.
uint8 REACHED_INITIAL=1
# Initial goal poses for pregrasp and go down are not feasible, but a different trajectory
# was found.
uint8 REACHED_SAMPLED=2

# FAILED, INITIAL_REACHED or SAMPLED_REACHED
uint8 status

# The final joint configuration of the robot at the end of the trajectory.
float64[] final_configuration

# The configuration space trajectory.
float64[] trajectory
